[package]
name = "app"
version = "0.0.0"
edition = "2018"
authors = []
license = ""
description = ""
repository = ""
documentation = ""
readme = ""
exclude = []
publish = false

[workspace]
include = ["crates/gen"]

[dependencies]
windows = "0.23.0"
bindings = { path = "bindings" }