[package]
name = "windows-app"
version = "0.2.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Windows App SDK"
repository = "https://github.com/microsoft/windows-app-rs"
documentation = "https://docs.rs/windows-app"
readme = "README.md"
exclude = [".github", "docs"]

[dependencies]
windows = { path = "/git/windows-rs" }

[build-dependencies]
windows = { path = "/git/windows-rs" }
