[package]
name = "windows_app_api"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
reader = { package = "windows_reader", version = "0.26" }
gen = { package = "windows_gen", version = "0.26" }
rayon = "1.5.1"
