[package]
name = "windows_app_api"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
reader = { package = "windows_reader", git = "https://github.com/microsoft/windows-rs" }
gen = { package = "windows_gen", git = "https://github.com/microsoft/windows-rs" }
rayon = "1.5.1"
