[package]
name = "bindings"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
windows = { version = "0.23.0", features = ["build"] }

[build-dependencies]
windows = { version = "0.23.0", features = ["build"] }
